<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>XML Sitemap</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
                <style type="text/css">
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
                        color: #444;
                        max-width: 1200px;
                        margin: 0 auto;
                        padding: 20px;
                    }
                    table {
                        border: none;
                        border-collapse: collapse;
                        width: 100%;
                        margin: 20px 0;
                    }
                    th {
                        background-color: #f8f9fa;
                        font-size: 14px;
                        padding: 12px;
                        text-align: left;
                        border-bottom: 1px solid #ddd;
                    }
                    td {
                        padding: 12px;
                        border-bottom: 1px solid #eee;
                        font-size: 14px;
                    }
                    tr:hover td {
                        background-color: #f8f9fa;
                    }
                    a {
                        color: #2271b1;
                        text-decoration: none;
                    }
                    a:hover {
                        color: #135e96;
                        text-decoration: underline;
                    }
                    .header {
                        background-color: #fff;
                        padding: 20px 0;
                        margin-bottom: 20px;
                        border-bottom: 1px solid #eee;
                    }
                    .header h1 {
                        margin: 0;
                        font-size: 24px;
                        font-weight: normal;
                        color: #23282d;
                    }
                    .desc {
                        margin: 10px 0;
                        color: #666;
                        font-size: 14px;
                    }
                    .count {
                        color: #666;
                        font-size: 14px;
                        margin-bottom: 20px;
                    }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>XML Sitemap</h1>
                    <p class="desc">This XML Sitemap is generated by Auto Repair Cost Calculator to make your content more visible for search engines.</p>
                </div>

                <div class="count">
                    Number of URLs: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
                </div>

                <table>
                    <tr>
                        <th>URL</th>
                        <th>Priority</th>
                        <th>Change Frequency</th>
                        <th>Last Modified</th>
                    </tr>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                        <tr>
                            <td>
                                <a href="{sitemap:loc}">
                                    <xsl:value-of select="sitemap:loc"/>
                                </a>
                            </td>
                            <td><xsl:value-of select="sitemap:priority"/></td>
                            <td><xsl:value-of select="sitemap:changefreq"/></td>
                            <td><xsl:value-of select="sitemap:lastmod"/></td>
                        </tr>
                    </xsl:for-each>
                </table>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>